blueprints/product/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, DecimalField, SelectField
from wtforms.validators import DataRequired, NumberRange

class ProductForm(FlaskForm):
    name = StringField('Name', render_kw={'maxlength': 126})
    internal_reference = StringField('Internal_reference', render_kw={'maxlength': 126})
    status = SelectField('Status', choices=[('active', 'active'), ('suspend', 'suspend')], coerce=str)

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        # Tidak ada relasi atau data terkait untuk field ini

blueprints/product/__init__.py
from flask import Blueprint

product_bp = Blueprint('product', __name__, template_folder='templates')

from . import routes  # Memanggil routes.py untuk mendefinisikan rute

blueprints/product/routes.py
from flask import render_template, request, redirect, url_for, flash, session
from . import product_bp

from sqlalchemy.orm import joinedload
from models import get_session
from models.product_model import Product
# Tambahkan model-model yang diperlukan

from .forms import ProductForm

@product_bp.route('/products')
def lists():
    db_session = get_session()
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    try:
        products = db_session.query(Product).options(
            # Tambahkan eager loading jika diperlukan
        ).all()

    finally:
        db_session.close()

    return render_template('products/index.html', products=products)

@product_bp.route('/product/new', methods=['GET', 'POST'])
def new():
    form = ProductForm()
    db_session = get_session()
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))

    # Ambil data tambahan jika diperlukan

    if form.validate_on_submit():
        # Menambahkan product baru
        product = Product(
            # Ambil data dari form
            name = form.name.data,
            internal_reference = form.internal_reference.data,
            status = form.status.data,
            created_by=session['user_id'],
            updated_by=None
        )
        db_session.add(product)
        db_session.commit()
        db_session.close()
        flash('Product created successfully!', 'success')
        return redirect(url_for('product.lists'))
    db_session.close()
    return render_template('products/new.html', form=form)

@product_bp.route('/product/<int:id>/edit', methods=['GET', 'POST'])
def edit(id):
    db_session = get_session()
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    try:
        product = db_session.query(Product).get(id)
        if not product:
            flash('Product not found!', 'danger')
            return redirect(url_for('product.lists'))

        form = ProductForm(obj=product)

        if form.validate_on_submit():
            # Update data
            product.name = form.name.data
            product.internal_reference = form.internal_reference.data
            product.status = form.status.data
            Product.updated_by = session['user_id']

            db_session.commit()
            flash('Product updated successfully!', 'success')
            return redirect(url_for('product.lists'))

        # Debug jika validasi form gagal
        if not form.validate_on_submit():
            flash(form.errors, 'danger')

        return render_template('products/edit.html', form=form, product=product)

    except Exception as e:
        db_session.rollback()
        flash('An error occurred while editing Product.', 'danger')
        print("Error:", e)
        return redirect(url_for('product.lists'))
    finally:
        db_session.close()

@product_bp.route('/product/<int:id>')
def show(id):
    db_session = get_session()
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    product = db_session.query(Product).get(id)

    db_session.close()
    if not product:
        flash('Product not found!', 'danger')
        return redirect(url_for('product.lists'))
    return render_template('products/show.html', product=product)

templates/products/edit.html
{% extends "layout.html" %}

{% block content %}
  <div class="card mb-4">
    <div class="card-header">
      Edit Detail
    </div>
    <div class="card-body">
			<form method="POST" action="{{ url_for('product.edit', id=product.id) }}">
				{{ form.csrf_token }}
			  {% include 'products/form.html' %}
			  <hr>
    		<a class="btn btn-secondary" href="{{ url_for('product.lists') }}">Back</a>
			  <button type="submit" class="btn btn-primary">Update</button>
			</form>
		</div>
	</div>
{% endblock %}

templates/products/form.html
                      <div class="row">
                        <div>
                          <label for="name">Name</label>
                          <input type="text" id="name" name="name" value="{{ product.name if product else '' }}" class="form-control">
                        </div>
                      </div>
                      <div class="row">
                        <div>
                          <label for="internal_reference">Internal_reference</label>
                          <input type="text" id="internal_reference" name="internal_reference" value="{{ product.internal_reference if product else '' }}" class="form-control">
                        </div>
                      </div>
                      <div class="row">
                        <div>
                          <label for="status">Status</label>
                          <select id="status" name="status" class="form-control">
                            <option value="active" {% if product and product.status == 'active' %}selected{% endif %}>active</option>
        <option value="suspend" {% if product and product.status == 'suspend' %}selected{% endif %}>suspend</option>
                          </select>
                        </div>
                      </div>

<!-- Tambahkan kolom lain sesuai kebutuhan -->

templates/products/index.html
{% extends "layout.html" %}

{% block content %}
<div class="card mb-4">
  <div class="card-header">
    <a class="btn btn-primary" href="{{ url_for('product.new') }}">Add</a>
  </div>
  <div class="card-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Internal_reference</th>
          <th>Status</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for product in products %}
        <tr>
          <td>{{ product.id }}</td>
          <td>{{ product.name }}</td>
          <td>{{ product.internal_reference }}</td>
          <td>{{ product.status }}</td>
          <td>
            <a href="{{ url_for('product.show', id=product.id) }}">Show</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

templates/products/new.html
{% extends "layout.html" %}

{% block content %}
  <div class="card mb-4">
    <div class="card-header">
      New
    </div>
    <div class="card-body">
			<form method="POST" action="{{ url_for('product.new') }}">
				{{ form.csrf_token }}
			  {% include 'products/form.html' %}
			  <hr>
        <a class="btn btn-secondary" href="{{ url_for('product.lists') }}">Back</a>
			  <button type="submit" class="btn btn-primary">Save</button>
			</form>
		</div>
	</div>
{% endblock %}

templates/products/show.html
{% extends "layout.html" %}

{% block content %}
<div class="card mb-4">
  <div class="card-header">
    Show Detail
  </div>
  <div class="card-body">
		<div>
      <div>Name: {{ product.name }}</div>
      <div>Internal_reference: {{ product.internal_reference }}</div>
      <div>Status: {{ product.status }}</div>
		</div>
		<hr>
    <a class="btn btn-secondary" href="{{ url_for('product.lists') }}">Back</a>
		<a class="btn btn-primary" href="{{ url_for('product.edit', id=product.id) }}">Edit</a>
	</div>
</div>
{% endblock %}