blueprints/employee/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, SelectField
from wtforms.validators import DataRequired
from models import get_session
from models.department_model import Department
from models.position_model import Position
from models.work_status_model import WorkStatus

class EmployeeForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    born_date = DateField('Born Date', validators=[DataRequired()])
    department = SelectField('Department', coerce=int)
    position = SelectField('Position', coerce=int)
    work_status = SelectField('Work Status', coerce=int)

    born_place = StringField('born_place')
    join_date = DateField('Join Date')
    image = StringField('image')
    gender = StringField('gender')
    nik = StringField('nik')
    phone_number = StringField('Phone Number', validators=[DataRequired()])
    email_address = StringField('email_address', validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        session = get_session()
        self.department.choices = [(d.id, d.name) for d in session.query(Department).all()]
        self.position.choices = [(p.id, p.name) for p in session.query(Position).all()]
        self.work_status.choices = [(ws.id, ws.name) for ws in session.query(WorkStatus).all()]
        session.close()

blueprints/employee/__init__.py
from flask import Blueprint

employee_bp = Blueprint('employee', __name__, template_folder='templates')

from . import routes  # Memanggil routes.py untuk mendefinisikan rute

blueprints/employee/routes.py
import os
import subprocess
from flask import render_template, request, redirect, url_for, flash, session, send_from_directory, jsonify
from werkzeug.utils import secure_filename
from dotenv import load_dotenv
from . import employee_bp

from sqlalchemy.orm import joinedload
from models import get_session
from models.employee_model import Employee
from models.department_model import Department
from models.position_model import Position
from models.work_status_model import WorkStatus

from .forms import EmployeeForm
# Memuat variabel dari file .env
load_dotenv()

# Ambil nilai CDN_HOST dari file .env
CDN_HOST = os.getenv('CDN_HOST')
CDN_USER = os.getenv('CDN_USER')
CDN_PASSWORD = os.getenv('CDN_PASSWORD')

@employee_bp.route('/employees')
def lists():
    # Gunakan db_session untuk query dengan eager loading
    db_session = get_session()
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    try:
        employees = db_session.query(Employee).options(
            joinedload(Employee.department),  # eager load department
            joinedload(Employee.position),  # eager load department
            joinedload(Employee.work_status)      # eager load work_status
        ).all()

    finally:
        db_session.close()

    # Kirim data ke template
    return render_template('employees/index.html', employees=employees)

@employee_bp.route('/employee/new', methods=['GET', 'POST'])
def new():
    form = EmployeeForm()
    db_session = get_session()
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    
    # Ambil daftar posisi, departemen, dan status kerja
    positions = db_session.query(Position).all()
    departments = db_session.query(Department).all()
    work_statuses = db_session.query(WorkStatus).all()

    if form.validate_on_submit():
        # Menambahkan employee baru
        employee = Employee(
            nik=form.nik.data,
            name=form.name.data,
            gender=form.gender.data,
            born_date=form.born_date.data,
            born_place=form.born_place.data,
            department_id=form.department.data,
            position_id=form.position.data,
            work_status_id=form.work_status.data,
            email_address=form.email_address.data,
            phone_number=form.phone_number.data,
            created_by=session['user_id'],
            updated_by=None
        )
        db_session.add(employee)
        db_session.commit()

        file = request.files.get('image')  # Ambil file dari form
        filename = ''
        
        if file and allowed_file(file.filename):
            # Ambil ekstensi file
            file_extension = os.path.splitext(file.filename)[1]
            
            # Gunakan ID employee untuk nama file unik
            filename = f"employee_{employee.id}{file_extension}"

            # Tentukan path penyimpanan file
            # upload_directory = os.path.join(f'\\\\{CDN_HOST}\\uploads$\\employee\\image')

            # Tentukan path penyimpanan file
            network_path = f"\\\\{CDN_HOST}\\uploads$\\employee\\image"

            # Melakukan login ke share network
            os.system(f'net use {network_path} /user:{CDN_USER} {CDN_PASSWORD}')
            os.makedirs(network_path, exist_ok=True)  # Buat folder jika belum ada

            filepath = os.path.join(network_path, filename)
            file.save(filepath)  # Simpan file ke path yang ditentukan
            # os.system(f'net use {network_path} /delete')

            # Perbarui employee dengan nama file gambar
            employee.image = filename
            db_session.commit()  # Commit perubahan untuk update image

        db_session.close()
        flash('Employee created successfully!', 'success')
        return redirect(url_for('employee.lists'))
    db_session.close()

    # Debug jika validasi form gagal
    if not form.validate_on_submit():
        flash(form.errors, 'danger')

    return render_template('employees/new.html', form=form, positions=positions, departments=departments, work_statuses=work_statuses)

@employee_bp.route('/employee/<int:id>/edit', methods=['GET', 'POST'])
def edit(id):
    # Mengambil db_session
    db_session = get_session()
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    try:
        # Ambil data employee berdasarkan ID
        employee = db_session.query(Employee).get(id)
        if not employee:
            flash('Employee not found!', 'danger')
            return redirect(url_for('employee.lists'))
        
        # Ambil daftar posisi, departemen, dan status kerja
        positions = db_session.query(Position).all()
        departments = db_session.query(Department).all()
        work_statuses = db_session.query(WorkStatus).all()

        # Bind data ke form
        form = EmployeeForm(obj=employee)

        # Proses ketika form dikirim
        if form.validate_on_submit():
            # Proses penghapusan gambar jika checkbox dicentang
            if 'remove_image' in request.form:
                if employee.image:
                    # Hapus file fisik jika ada
                    # image_path = os.path.join(os.getcwd(), 'uploads', 'employee', 'image', employee.image)
                    # image_path = os.path.join(f'\\\\{CDN_HOST}\\uploads$\\employee\\image', employee.image)

                    # Menentukan kredensial
                    network_path = f"\\\\{CDN_HOST}\\uploads$\\employee\\image"

                    # Melakukan login ke share network
                    os.system(f'net use {network_path} /user:{CDN_USER} {CDN_PASSWORD}')
                    
                    # Cek apakah bisa mengakses file setelah login
                    image_path = os.path.join(network_path, 'employee_5.jpeg')

                    if os.path.exists(image_path):
                        os.remove(image_path)
                    employee.image = None  # Hapus referensi gambar dari database
                    # os.system(f'net use {network_path} /delete')

            file = request.files.get('image')  # Ambil file dari form
            
            if file and allowed_file(file.filename):
                # Ambil ekstensi file
                file_extension = os.path.splitext(file.filename)[1]  # Mendapatkan .jpg, .png, dll.
                
                # Tentukan nama file unik dengan ID employee
                filename = f"employee_{id}{file_extension}"
                
                # Tentukan path penyimpanan file
                network_path = f"\\\\{CDN_HOST}\\uploads$\\employee\\image"

                # Melakukan login ke share network
                os.system(f'net use {network_path} /user:{CDN_USER} {CDN_PASSWORD}')
                # upload_directory = os.path.join(f'\\\\{CDN_HOST}\\uploads$\\employee\\image')
                os.makedirs(network_path, exist_ok=True)  # Buat folder jika belum ada

                filepath = os.path.join(network_path, filename)
                file.save(filepath)  # Simpan file ke path yang ditentukan
                # os.system(f'net use {network_path} /delete')

                employee.image = filename

            # Update data employee
            employee.nik = form.nik.data
            employee.name = form.name.data
            employee.gender = form.gender.data
            employee.born_date = form.born_date.data
            employee.born_place = form.born_place.data
            employee.join_date = form.join_date.data
            employee.department_id = form.department.data
            employee.position_id = form.position.data
            employee.work_status_id = form.work_status.data
            employee.phone_number = form.phone_number.data
            employee.email_address = form.email_address.data
            employee.updated_by = session['user_id']
            
            # Commit perubahan
            db_session.commit()
            flash('Employee updated successfully!', 'success')
            return redirect(url_for('employee.lists'))
        
        # Debug jika validasi form gagal
        if not form.validate_on_submit():
            flash(form.errors, 'danger')
        
        # Render template edit
        return render_template(
            'employees/edit.html',
            form=form,
            employee=employee,
            positions=positions,
            departments=departments,
            work_statuses=work_statuses
        )
    except Exception as e:
        db_session.rollback()  # Rollback jika ada error
        flash('An error occurred while editing employee.', 'danger')
        print("Error:", e)
        return redirect(url_for('employee.lists'))
    finally:
        db_session.close()  # Selalu tutup db_session


@employee_bp.route('/employee/<int:id>')
def show(id):
    db_session = get_session()
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    employee = db_session.query(Employee).get(id)

    # Ambil daftar posisi, departemen, dan status kerja
    positions = db_session.query(Position).all()
    departments = db_session.query(Department).all()
    work_statuses = db_session.query(WorkStatus).all()

    db_session.close()
    if not employee:
        flash('Employee not found!', 'danger')
        return redirect(url_for('employee.employees'))
    return render_template('employees/show.html', employee=employee, disabled='true', positions=positions, departments=departments, work_statuses=work_statuses)

@employee_bp.route('/employee/uploads/<filename>')
def uploaded_file(filename):
    load_dotenv()

    CDN_HOST = os.getenv('CDN_HOST')
    CDN_USER = os.getenv('CDN_USER')
    CDN_PASSWORD = os.getenv('CDN_PASSWORD')

    # Tentukan path menggunakan CDN_HOST untuk file yang di-upload
    UPLOAD_FOLDER = os.path.join(f'\\\\{CDN_HOST}\\uploads$\\employee\\image')

    # Melakukan login ke share network dan mengecek status koneksi
    network_path = f'\\\\{CDN_HOST}\\uploads$'

templates/employees/edit.html
<!DOCTYPE html><!--
* CoreUI - Free Bootstrap Admin Template
* @version v5.1.1
* @link https://coreui.io/product/free-bootstrap-admin-template/
* Copyright (c) 2024 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://github.com/coreui/coreui-free-bootstrap-admin-template/blob/main/LICENSE)
-->
<html lang="en">
  <head>
    <base href="{{ url_for('static', filename='./') }}">
    <!-- Include the common head content -->
    {% include 'head.html' %}
  </head>
  <body>
    <div class="sidebar sidebar-dark sidebar-fixed border-end" id="sidebar">
      <!-- Include the sidebar from sidebar.html -->
      {% include 'sidebar.html' %}
    </div>
    <div class="wrapper d-flex flex-column min-vh-100">
      <header class="header header-sticky p-0 mb-4">
        <!-- Include the navbar from navbar.html -->
        {% include 'navbar.html' %}

        <div class="container-fluid px-4">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-0">
              <li class="breadcrumb-item"><a href="#">Home</a>
              </li>
              <li class="breadcrumb-item active"><span>Employees</span>
              </li>
            </ol>
          </nav>
        </div>
      </header>

      <div class="body flex-grow-1">
        <div class="container-lg px-4">
          <div class="card mb-4">
            <div class="card-header">
              Employee Detail
            </div>
            <div class="card-body">
              <form action="{{ url_for('employee.edit', id=employee.id) }}" method="POST" enctype="multipart/form-data">
                {{ form.csrf_token }}
                {% if employee %}
                  {% include 'employees/form.html' %}
                {% else %}
                    <p>Employee not found</p>
                {% endif %}
                
                <a class="btn btn-secondary" href="{{ url_for('employee.lists') }}">Back</a>
                <button type="submit" class="btn btn-primary">Save</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Include the footer from footer.html -->
      {% include 'footer.html' %}
    </div>
    
    <!-- Include the script from script.html -->
    {% include 'script.html' %}

        <!-- jQuery, Popper.js, dan Bootstrap JS untuk modal -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


  </body>
</html>

templates/employees/form.html
<div class="row">
    <!-- Employee Image Section -->
    <div class="col-md-auto">
        <div class="card">
            <div class="card-body text-center">
                <!-- Display employee image or default image -->
                {% if employee and employee.image %}
                    <img src="" 
                         class="img-thumbnail" 
                         id="employee_image" width="100"
                         alt="Employee Image">
                {% else %}
                    <img src="{{ url_for('static', filename='images/user.svg') }}" alt="Default Image" width="100">
                {% endif %}

                <script>
                  // Mendapatkan URL gambar yang akan di-load
                  {% if employee and employee.image %}
                    var imageUrl = "{{ url_for('employee.uploaded_file', filename=employee.image) }}";

                    // Mengecek gambar menggunakan fetch untuk menangani error
                    fetch(imageUrl)
                        .then(response => {
                            if (!response.ok) {
                                throw new Error('Image not found or access denied.');
                            }
                            // Jika berhasil, set gambar
                            document.getElementById('employee_image').src = imageUrl;
                        })
                        .catch(error => {
                            // Jika error terjadi, tampilkan gambar error dan set title dengan pesan error
                            document.getElementById('employee_image').src = "{{ url_for('static', filename='images/error-image-photo-icon.svg') }}";
                            document.getElementById('employee_image').title = error.message;  // Set title dengan pesan error
                        });
                  {% endif %}
                </script>

                {% if disabled == "true" %}
                {% else %}
                  <li class="nav-item dropdown list-unstyled">
                    <button class="btn btn-link nav-link py-2 px-2 d-flex align-items-center" type="button" aria-expanded="false" data-coreui-toggle="dropdown">
                      <svg class="icon icon-lg theme-icon-active">
                        <use xlink:href="/static/vendors/@coreui/icons/svg/free.svg#cil-pencil"></use>
                      </svg>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end" style="--cui-dropdown-min-width: 8rem;">
                      <li>
                          <button class="dropdown-item" type="button">
                              <input type="file" class="form-control" id="employee_image" name="image">
                              <input type="hidden" id="employee_image_cache" name="image_cache">
                          </button>
                      </li>
                      <hr>
                      {% if employee and employee.image %}
                          <li>
                              <label for="employee_remove_image" class="dropdown-item">
                                  <input type="checkbox" id="employee_remove_image" name="remove_image"> Remove
                              </label>
                          </li>
                      {% endif %}

                    </ul>
                  </li>
                {% endif %}
            </div>
        </div>
    </div>


    <!-- Employee Details Section -->
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <!-- NIK, Name, Department -->
                <div class="row mb-3">
                    <div class="col-md-4">
                        <label for="employee_nik" class="form-label">NIK</label>
                        <input type="text" id="employee_nik" class="form-control" name="nik" value="{{ employee.nik if employee else '' }}" {% if disabled == "true" %} disabled {% endif %}>
                    </div>
                    <div class="col-md-4">
                      <label for="employeeName">Name</label>
                      <input type="text" class="form-control" id="employeeName" name="name"  
                        {% if employee %} value="{{ employee.name }}" {% else %} value="" {% endif %} 
                        {% if disabled == "true" %} disabled {% endif %} required>
                    </div>
                    <div class="col-md-4">
                      <label for="employeeDepartment">Department</label>
                      <select class="form-control" id="employeeDepartment" name="department" 
                        {% if disabled == 'true' %} disabled {% endif %} required>
                        <option value="">Select Department</option>
                        {% for department in departments %}
                          <option value="{{ department.id }}" 
                            {% if employee and department.id == employee.department_id %} selected {% endif %}>
                            {{ department.name }}
                          </option>
                        {% endfor %}
                      </select>
                    </div>
                </div>

                <!-- Position, Work Status, Place of Birth -->
                <div class="row mb-3">
                    <div class="col-md-4">
                      <label for="employeePosition">Position</label>
                      <select class="form-control" id="employeePosition" name="position" 
                        {% if disabled == 'true' %} disabled {% endif %} required>
                        <option value="">Select Position</option>
                        {% for position in positions %}
                          <option value="{{ position.id }}" 
                            {% if employee and position.id == employee.position_id %} selected {% endif %}>
                            {{ position.name }}
                          </option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="col-md-4">
                      <label for="employeeWorkStatus">WorkStatus</label>
                      <select class="form-control" id="employeeWorkStatus" name="work_status" 
                        {% if disabled == 'true' %} disabled {% endif %} required>
                        <option value="">Select WorkStatus</option>
                        {% for work_status in work_statuses %}
                          <option value="{{ work_status.id }}" 
                            {% if employee and work_status.id == employee.work_status_id %} selected {% endif %}>
                            {{ work_status.name }}
                          </option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="col-md-4">
                        <label for="employee_born_place" class="form-label">Place of Birth</label>
                        <input type="text" id="employee_born_place" class="form-control" name="born_place" required value="{{ employee.born_place if employee else '' }}" {% if disabled == "true" %} disabled {% endif %}>
                    </div>
                </div>

                <!-- Date of Birth, Join Date -->
                <div class="row mb-3">
                    <div class="col-md-4">
                      <label for="employeeBornDate">Date of Birth</label>
                      <input type="date" class="form-control" id="employeeBornDate" name="born_date"  
                        {% if employee %} value="{{ employee.born_date }}" {% else %} value="" {% endif %} 
                        {% if disabled == "true" %} disabled {% endif %} required>
                    </div>
                    <div class="col-md-4">
                        <label for="employee_join_date" class="form-label">Join Date</label>
                        <input type="date" id="employee_join_date" class="form-control" name="join_date" required value="{{ employee.join_date if employee else '' }}" {% if disabled == "true" %} disabled {% endif %}>
                    </div>
                </div>

                <!-- Gender, Contacts -->
                <div class="row mb-3">
                    <div class="col-md-4">
                        <label for="employee_gender" class="form-label">Gender</label>
                        <select class="form-select" id="employee_gender" name="gender" {% if disabled == 'true' %} disabled {% endif %}>
                            <option value="Laki laki" {% if employee and employee.gender == 'Laki laki' %} selected {% endif %}>Laki laki</option>
                            <option value="Perempuan" {% if employee and employee.gender == 'Perempuan' %} selected {% endif %}>Perempuan</option>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="employee_phone_number" class="form-label">Phone Number</label>
                        <input type="text" id="employee_phone_number" class="form-control" name="phone_number" value="{{ employee.phone_number if employee else '' }}" {% if disabled == "true" %} disabled {% endif %}>
                    </div>
                    <div class="col-md-4">
                        <label for="employee_email_address" class="form-label">Email</label>
                        <input type="email" id="employee_email_address" class="form-control" name="email_address" value="{{ employee.email_address if employee else '' }}" {% if disabled == "true" %} disabled {% endif %}>
                    </div>
                </div>

                <!-- Work Schedule -->
                <div class="row mb-3">
                    <div class="col-md-4">
                        <label for="employee_work_schedule" class="form-label">Work Schedule</label>
                        <select class="form-select" id="employee_work_schedule" name="work_schedule" {% if disabled == 'true' %} disabled {% endif %}>
                            <option value="6-2" {% if employee and employee.work_schedule == '6-2' %} selected {% endif %}>6-2</option>
                            <option value="6-0" {% if employee and employee.work_schedule == '6-0' %} selected {% endif %}>6-0</option>
                            <option value="5-0" {% if employee and employee.work_schedule == '5-0' %} selected {% endif %}>5-0</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/employees/index.html
{% extends "layout.html" %}

{% block content %}
  <div class="card mb-4">
    <div class="card-header">
    	<a class="btn btn-primary" href="{{ url_for('employee.new') }}">Add</a>
    </div>
    <div class="card-body">
    	<table class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Action</th>
            <th>Name</th>
            <th>Position</th>
            <th>Department</th>
          </tr>
        </thead>
        <tbody>
          {% if employees %}
            {% for employee in employees %}
            <tr>
              <td>{{ employee.id }}</td>
              <td><a href="{{ url_for('employee.show', id=employee.id) }}">View Details</a></td>
              <td>{{ employee.name }}</td>
              <td>{{ employee.position.name }}</td>
              <td>{{ employee.department.name }}</td>
            </tr>
            {% endfor %}
          {% else %}
            <tr>
              <td colspan="4">No employees found</td>
            </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

templates/employees/new.html
<!DOCTYPE html><!--
* CoreUI - Free Bootstrap Admin Template
* @version v5.1.1
* @link https://coreui.io/product/free-bootstrap-admin-template/
* Copyright (c) 2024 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://github.com/coreui/coreui-free-bootstrap-admin-template/blob/main/LICENSE)
-->
<html lang="en">
  <head>
    <base href="{{ url_for('static', filename='./') }}">
    <!-- Include the common head content -->
    {% include 'head.html' %}
  </head>
  <body>
    <div class="sidebar sidebar-dark sidebar-fixed border-end" id="sidebar">
      <!-- Include the sidebar from sidebar.html -->
      {% include 'sidebar.html' %}
    </div>
    <div class="wrapper d-flex flex-column min-vh-100">
      <header class="header header-sticky p-0 mb-4">
        <!-- Include the navbar from navbar.html -->
        {% include 'navbar.html' %}

        <div class="container-fluid px-4">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-0">
              <li class="breadcrumb-item"><a href="#">Home</a>
              </li>
              <li class="breadcrumb-item active"><span>Employees</span>
              </li>
            </ol>
          </nav>
        </div>
      </header>

      <div class="body flex-grow-1">
        <div class="container-lg px-4">
          <div class="card mb-4">
            <div class="card-header">
              Employee Detail
            </div>
            <div class="card-body">
              <!-- Form untuk menambah employee -->
              <form action="{{ url_for('employee.new') }}" method="POST" enctype="multipart/form-data">
                {{ form.csrf_token }}
                {% include 'employees/form.html' %}
                
                <a class="btn btn-secondary" href="{{ url_for('employee.lists') }}">Back</a>
                <button type="submit" class="btn btn-primary">Save</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Include the footer from footer.html -->
      {% include 'footer.html' %}
    </div>
    
    <!-- Include the script from script.html -->
    {% include 'script.html' %}

    <!-- jQuery, Popper.js, dan Bootstrap JS untuk modal -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


  </body>
</html>

templates/employees/show.html
<!DOCTYPE html><!--
* CoreUI - Free Bootstrap Admin Template
* @version v5.1.1
* @link https://coreui.io/product/free-bootstrap-admin-template/
* Copyright (c) 2024 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://github.com/coreui/coreui-free-bootstrap-admin-template/blob/main/LICENSE)
-->
<html lang="en">
  <head>
    <base href="{{ url_for('static', filename='./') }}">
    <!-- Include the common head content -->
    {% include 'head.html' %}
  </head>
  <body>
    <div class="sidebar sidebar-dark sidebar-fixed border-end" id="sidebar">
      <!-- Include the sidebar from sidebar.html -->
      {% include 'sidebar.html' %}
    </div>
    <div class="wrapper d-flex flex-column min-vh-100">
      <header class="header header-sticky p-0 mb-4">
        <!-- Include the navbar from navbar.html -->
        {% include 'navbar.html' %}

        <div class="container-fluid px-4">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-0">
              <li class="breadcrumb-item"><a href="#">Home</a>
              </li>
              <li class="breadcrumb-item active"><span>Employees</span>
              </li>
            </ol>
          </nav>
        </div>
      </header>

      <div class="body flex-grow-1">
        <div class="container-lg px-4">
          <div class="card mb-4">
            <div class="card-header">
              Employee Detail
            </div>
            <div class="card-body">

              {% if employee %}
                {% include 'employees/form.html' %}
              {% else %}
                  <p>Employee not found</p>
              {% endif %}
              
              <a class="btn btn-secondary" href="{{ url_for('employee.lists') }}">Back</a>
              <a class="btn btn-primary" href="{{ url_for('employee.edit', id=employee.id) }}">Edit</a>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Include the footer from footer.html -->
      {% include 'footer.html' %}
    </div>
    
    <!-- Include the script from script.html -->
    {% include 'script.html' %}

        <!-- jQuery, Popper.js, dan Bootstrap JS untuk modal -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


  </body>
</html>