blueprints/currency/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, DecimalField, SelectField
from wtforms.validators import DataRequired, NumberRange

class CurrencyForm(FlaskForm):
    name = StringField('Name', render_kw={'maxlength': 255})
    symbol = StringField('Symbol', render_kw={'maxlength': 16})
    precision_digit = IntegerField('Precision_digit', validators=[NumberRange(min=0)])

    def __init__(self, *args, **kwargs):
        super(CurrencyForm, self).__init__(*args, **kwargs)
        # Tidak ada relasi atau data terkait untuk field ini

blueprints/currency/__init__.py
from flask import Blueprint

currency_bp = Blueprint('currency', __name__, template_folder='templates')

from . import routes  # Memanggil routes.py untuk mendefinisikan rute

blueprints/currency/routes.py
from flask import render_template, request, redirect, url_for, flash, session
from . import currency_bp

from sqlalchemy.orm import joinedload
from models import get_session
from models.currency_model import Currency
# Tambahkan model-model yang diperlukan

from .forms import CurrencyForm

@currency_bp.route('/currencies')
def lists():
    db_session = get_session()
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    try:
        currencies = db_session.query(Currency).options(
            # Tambahkan eager loading jika diperlukan
        ).all()

    finally:
        db_session.close()

    return render_template('currencies/index.html', currencies=currencies)

@currency_bp.route('/currency/new', methods=['GET', 'POST'])
def new():
    form = CurrencyForm()
    db_session = get_session()
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))

    # Ambil data tambahan jika diperlukan

    if form.validate_on_submit():
        # Menambahkan currency baru
        currency = Currency(
            # Ambil data dari form
            name = form.name.data,
            symbol = form.symbol.data,
            precision_digit = form.precision_digit.data,
            created_by=session['user_id'],
            updated_by=None
        )
        db_session.add(currency)
        db_session.commit()
        db_session.close()
        flash('Currency created successfully!', 'success')
        return redirect(url_for('currency.lists'))
    db_session.close()
    return render_template('currencies/new.html', form=form)

@currency_bp.route('/currency/<int:id>/edit', methods=['GET', 'POST'])
def edit(id):
    db_session = get_session()
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    try:
        currency = db_session.query(Currency).get(id)
        if not currency:
            flash('Currency not found!', 'danger')
            return redirect(url_for('currency.lists'))

        form = CurrencyForm(obj=currency)

        if form.validate_on_submit():
            # Update data
            currency.name = form.name.data
            currency.symbol = form.symbol.data
            currency.precision_digit = form.precision_digit.data
            Currency.updated_by = session['user_id']

            db_session.commit()
            flash('Currency updated successfully!', 'success')
            return redirect(url_for('currency.lists'))

        # Debug jika validasi form gagal
        if not form.validate_on_submit():
            flash(form.errors, 'danger')

        return render_template('currencies/edit.html', form=form, currency=currency)

    except Exception as e:
        db_session.rollback()
        flash('An error occurred while editing Currency.', 'danger')
        print("Error:", e)
        return redirect(url_for('currency.lists'))
    finally:
        db_session.close()

@currency_bp.route('/currency/<int:id>')
def show(id):
    db_session = get_session()
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    currency = db_session.query(Currency).get(id)

    db_session.close()
    if not currency:
        flash('Currency not found!', 'danger')
        return redirect(url_for('currency.lists'))
    return render_template('currencies/show.html', currency=currency)

templates/currencies/edit.html
{% extends "layout.html" %}

{% block content %}
  <div class="card mb-4">
    <div class="card-header">
      Edit Detail
    </div>
    <div class="card-body">
			<form method="POST" action="{{ url_for('currency.edit', id=currency.id) }}">
				{{ form.csrf_token }}
			  {% include 'currencies/form.html' %}
			  <hr>
    		<a class="btn btn-secondary" href="{{ url_for('currency.lists') }}">Back</a>
			  <button type="submit" class="btn btn-primary">Update</button>
			</form>
		</div>
	</div>
{% endblock %}

templates/currencies/form.html
                      <div class="row">
                        <div>
                          <label for="name">Name</label>
                          <input type="text" id="name" name="name" value="{{ currency.name if currency else '' }}" class="form-control">
                        </div>
                      </div>
                      <div class="row">
                        <div>
                          <label for="symbol">Symbol</label>
                          <input type="text" id="symbol" name="symbol" value="{{ currency.symbol if currency else '' }}" class="form-control">
                        </div>
                      </div>
                      <div class="row">
                        <div>
                          <label for="precision_digit">Precision_digit</label>
                          <input type="text" id="precision_digit" name="precision_digit" value="{{ currency.precision_digit if currency else '' }}" class="form-control">
                        </div>
                      </div>

<!-- Tambahkan kolom lain sesuai kebutuhan -->

templates/currencies/index.html
{% extends "layout.html" %}

{% block content %}
<div class="card mb-4">
  <div class="card-header">
    <a class="btn btn-primary" href="{{ url_for('currency.new') }}">Add</a>
  </div>
  <div class="card-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Symbol</th>
          <th>Precision_digit</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for currency in currencies %}
        <tr>
          <td>{{ currency.id }}</td>
          <td>{{ currency.name }}</td>
          <td>{{ currency.symbol }}</td>
          <td>{{ currency.precision_digit }}</td>
          <td>
            <a href="{{ url_for('currency.show', id=currency.id) }}">Show</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

templates/currencies/new.html
{% extends "layout.html" %}

{% block content %}
  <div class="card mb-4">
    <div class="card-header">
      New
    </div>
    <div class="card-body">
			<form method="POST" action="{{ url_for('currency.new') }}">
				{{ form.csrf_token }}
			  {% include 'currencies/form.html' %}
			  <hr>
        <a class="btn btn-secondary" href="{{ url_for('currency.lists') }}">Back</a>
			  <button type="submit" class="btn btn-primary">Save</button>
			</form>
		</div>
	</div>
{% endblock %}

templates/currencies/show.html
{% extends "layout.html" %}

{% block content %}
<div class="card mb-4">
  <div class="card-header">
    Show Detail
  </div>
  <div class="card-body">
		<div>
      <div>Name: {{ currency.name }}</div>
      <div>Symbol: {{ currency.symbol }}</div>
      <div>Precision_digit: {{ currency.precision_digit }}</div>
		</div>
		<hr>
    <a class="btn btn-secondary" href="{{ url_for('currency.lists') }}">Back</a>
		<a class="btn btn-primary" href="{{ url_for('currency.edit', id=currency.id) }}">Edit</a>
	</div>
</div>
{% endblock %}